# Generated by Django 2.0 on 2018-12-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('flight_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Flight ID')),
                ('mission_name', models.CharField(max_length=80, verbose_name='Mission Name')),
                ('mission_patch', models.CharField(max_length=200, verbose_name='Mission Patch')),
                ('video_link', models.CharField(max_length=200, verbose_name='Video Link')),
                ('rocket_name', models.CharField(max_length=200, verbose_name='Rocket Name')),
                ('launch_date_utc', models.CharField(max_length=30, verbose_name='Date UCT')),
            ],
        ),
    ]
